name: Continuous Integration

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CI: true
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Downloading dependencies
        run: npm ci

      - name: Code quality
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build
